spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # railway用环境变量读取mysql，自动读取项目绑定的mysql参数
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:/com/southwind/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  # railway强制使用平台分配端口${PORT}，本地运行默认8181
  port: ${PORT:8181}
  servlet:
    context-path: /api
